server:
  port: 8040
  #应用名称(nacos将该名称作为服务名称)
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.161.23:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
    loadbalancer:
      ribbon:
        enabled: false
